// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oganesyan_WebAPI.Data;

#nullable disable

namespace Oganesyan_WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415170017_RemoveTelegram")]
    partial class RemoveTelegram
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Oganesyan_WebAPI.Models.DatabaseDeployment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DatabaseMetaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DbMetaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DeployedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeployed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhysicaDatabaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DbMetaId");

                    b.HasIndex("DatabaseMetaId", "DbMetaId")
                        .IsUnique();

                    b.ToTable("DatabaseDeployments");
                });

            modelBuilder.Entity("Oganesyan_WebAPI.Models.DatabaseMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateScriptTemplate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErdImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogicalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatabaseMetas");
                });

            modelBuilder.Entity("Oganesyan_WebAPI.Models.DbMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("dbType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("dbType")
                        .IsUnique();

                    b.ToTable("DbMetas");
                });

            modelBuilder.Entity("Oganesyan_WebAPI.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DatabaseMetaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseMetaId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Oganesyan_WebAPI.Models.Solution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeploymentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("Oganesyan_WebAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InArchive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Oganesyan_WebAPI.Models.DatabaseDeployment", b =>
                {
                    b.HasOne("Oganesyan_WebAPI.Models.DatabaseMeta", "DatabaseMeta")
                        .WithMany("Deployments")
                        .HasForeignKey("DatabaseMetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oganesyan_WebAPI.Models.DbMeta", "DbMeta")
                        .WithMany()
                        .HasForeignKey("DbMetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatabaseMeta");

                    b.Navigation("DbMeta");
                });

            modelBuilder.Entity("Oganesyan_WebAPI.Models.Exercise", b =>
                {
                    b.HasOne("Oganesyan_WebAPI.Models.DatabaseMeta", "DatabaseMeta")
                        .WithMany()
                        .HasForeignKey("DatabaseMetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatabaseMeta");
                });

            modelBuilder.Entity("Oganesyan_WebAPI.Models.Solution", b =>
                {
                    b.HasOne("Oganesyan_WebAPI.Models.DatabaseDeployment", "Deployment")
                        .WithMany()
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oganesyan_WebAPI.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Oganesyan_WebAPI.Models.DatabaseMeta", b =>
                {
                    b.Navigation("Deployments");
                });
#pragma warning restore 612, 618
        }
    }
}
